### ISSUE TITLE
Trouble with Vertical Clock

### ISSUE THREAD

**Issue by olenz** [Emdek/plasmoid-adjustable-clock#10]
Hi!
I now seem to have trouble with my Vertical Clock theme. I have tried for quite a while: in a horizontal panel or on the desktop, it is no problem. But when using a vertical panel, the clock display disappears completely, and shifts everything below the clock off screen.
It looks as though this is actually caused by the fifth "div" element, it seems to be able to display only four div elements in a vertical panel.
Any ideas?
Olaf

**Comment by olenz** [comment]
I just noticed that the same holds for the "Calendar" theme: I can't put it into a vertical panel.

**Comment by Emdek** [comment]
Thanks for report, it seems to be an issue with minimum size.
It should be improved a bit now but switching themes will cause it to grow (only in vertical panels) and there are few other issues...

**Comment by Emdek** [comment]
Should be fixed now.
