### ISSUE TITLE
No Tooltip

### ISSUE THREAD

**Issue by X4** [Emdek/plasmoid-adjustable-clock#11]
Hi,

firstly I want tou apploud you to having this plasmoid improved so much that I believe it should become the default in KDE.

I have a minor isse, having clients in many different areas of the world and trying to find out what time they have right now is time-consuming. The tooltip that showed different timezones is gone, could you readd it?

To have the tooltip display other adjustable clock design with made to show different timezone would look great. Other than that, I can't spot any issue, really nice work!!
(Wish I could help you, really, but I'm too busy right now..)

**Comment by Emdek** [comment]
Hello

Which versions of applet and KDE are you using?

Currently applet uses standard (the same like all other clocks) clock tooltip unless there are set values for _toolTipExpressionMain_ and _toolTipExpressionSub_ (custom expressions or empty values to disable tooltip completely).
Please check if there are such keys set (in _~/.kde/share/config/plasma-desktop-appletsrc/_).
If not then check if other clocks have proper tooltips.

To get current time for different time zones you need to select them in configuration dialog, then they will be shown in tooltip (at least when using default expression).

**Comment by X4** [comment]
I emerged from git, which means I have the current version of adjustable-clock.
KDE is at version 4.10.4
Hmm the standard clock has no tooltip too.
~/.kde4/share/config/plasma-desktop-appletsrc doesn't contain these values

```
Oh.. I got it. I disabled "Show Information" in the Workspace settings..
```

Sorry Emdek.

**Comment by Emdek** [comment]
No problem. ;-)
