### ISSUE TITLE
AM/PM should not be displayed in beClock when in 24 hours mode

### ISSUE THREAD

**Issue by gdebure** [Emdek/plasmoid-adjustable-clock#14]
I'm using the beClock in 24 hours mode, and like it a lot ! However, the "AM/PM" indicator is of no use in this mode, and I think it should be removed. I tried to fix it myself by updating the source, but the only way I could find would be setting opacity to 0.0 on the ".back" class.

Any better way to do it ?

**Comment by Emdek** [comment]
You can also remove this line:

```
    <div class="back" component="TimeOfDay"></div>
```

I think that indicator is important part of design of that clock, so I would go for separate option to disable it, instead of disabling it always if mode is set to 24 hours.

**Comment by gdebure** [comment]
Thanks for the workaround and quick fix :)
