### ISSUE TITLE
Store personal themes in config, not in session?

### ISSUE THREAD

**Issue by olenz** [Emdek/plasmoid-adjustable-clock#3]
Currently, when I create a personal theme, it is stored in `config/plasma-desktop-appletsrc`. The bad thing about this is, that when I accidentally delete the clock, the theme is also gone.  Also, it is not possible to create more than one instance of the theme.

To avoid that, it would be nice to store the theme in an own config file.

**Comment by Emdek** [comment]
Interesting idea, custom themes could be placed in XML file (with syntax like that one for built in ones) located in standard data path.

**Comment by Emdek** [comment]
Fixed in a902fb869969a88b41e08c888607e5e874cf306f.

**Comment by olenz** [comment]
Nice! Thank you!
