### ISSUE TITLE
Time zone interference between multiple instances.

### ISSUE THREAD

**Issue by wks** [Emdek/plasmoid-adjustable-clock#5]
I put multiple instances of this plasmoid on the panel to track the times in multiple cities in the world.

When creating multiple instances and set each to a different time zone, such setting in one instance may interfere with other instances.

How to reproduce:
1. Create two instances of adjustable clocks on the panel.
2. Set the "theme" of both clocks to show timezone (city name) and time (including hour, minute and second)
3. Set the first instance's "time zone" to one place.
4. In the second instance's "time zone"  setting, select multiple cities.
5. Point the mouse cursor to the second instance and scroll the mouse wheel. This will change the current time zone of the second instance.

What actually happens:
1. After one second (when the first clock should be refreshed), the "time zone" shown on the first instance changed to that of the second instance.

What should happen:
1. The first instance should keep its own time zone.

Possible causes:

Some data structures are shared between the two instances, but they should be instance-specific.

**Comment by Emdek** [comment]
Confirmed, thanks for report.
I'm going to rewrite part that most probably causes this issue while introducing support for JavaScript API for querying date and time.

**Comment by Emdek** [comment]
Fixed in e2c523ab72cd46d38d1087b54b7f262e39104ddf.
