### ISSUE TITLE
Clock doesnt remember time zone

### ISSUE THREAD

**Issue by gustavogenovese** [Emdek/plasmoid-adjustable-clock#9]
I'm using the version 4.0 of this plasmoid in KDE 4.10.2 (Archlinux). I've added a clock to my desktop with a different timezone. When you create the plasmoid the time is displayed correctly in the timezone specified, but when you restart the computer, the clock shows the local time again. 
If you open the plasmoid settings and press "OK" (without changing anything), the clock shows again the time in the correct timezone

**Comment by Emdek** [comment]
Thanks for report, should be fixed in 01d2373851.
There seems to be an issue in Plasma that tricks applets to try to load configuration too early which results in invalid / default values.
